# {{group_name}} – Dunst Theme
# Generated by generate-themes.sh
# Symlinked to ~/.config/dunst/dunstrc by theme-toggle.sh

[global]
    monitor = 0
    follow = mouse
    width = 340
    height = 120
    origin = top-right
    offset = 15x15
    scale = 0
    notification_limit = 5
    gap_size = 5
    progress_bar = true
    progress_bar_height = 10
    progress_bar_frame_width = 1
    progress_bar_min_width = 150
    progress_bar_max_width = 300
    progress_bar_corner_radius = 4
    indicate_hidden = yes
    transparency = {{transparency}}
    separator_height = 2
    padding = 12
    horizontal_padding = 14
    text_icon_padding = 8
    frame_width = 2
    frame_color = "#{{accent}}"
    separator_color = frame
    sort = yes
    idle_threshold = 120
    font = JetBrainsMono Nerd Font 10
    line_height = 0
    markup = full
    format = "<b>%s</b>\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 60
    word_wrap = yes
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes
    icon_theme = Sweet-Rainbow
    enable_recursive_icon_lookup = true
    icon_position = left
    min_icon_size = 32
    max_icon_size = 64
    corner_radius = 12
    sticky_history = yes
    history_length = 20
    dmenu = /usr/bin/wofi --dmenu --prompt "Notifications"
    browser = /usr/bin/chromium --new-tab
    always_run_script = true
    title = Dunst
    class = Dunst
    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all
    ignore_dbusclose = false

[urgency_low]
    background = "#{{bg_base}}"
    foreground = "#{{text}}"
    frame_color = "#{{bg_surface}}"
    timeout = 5
    icon = dialog-information

[urgency_normal]
    background = "#{{bg_base}}"
    foreground = "#{{text}}"
    frame_color = "#{{accent}}"
    timeout = 8

[urgency_critical]
    background = "#{{bg_base}}"
    foreground = "#{{red}}"
    frame_color = "#{{red}}"
    timeout = 0
    icon = dialog-error

[volume]
    appname = volume
    format = "<b>Volume</b>\n%b"
    timeout = 2

[brightness]
    appname = brightness
    format = "<b>Brightness</b>\n%b"
    timeout = 2
