// {{group_name}} – Fastfetch Configuration
// Generated by generate-themes.sh
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",

    "logo": {
        "source": "arch",
        "color": {
            "1": "#{{accent}}",
            "2": "#{{accent_secondary}}"
        },
        "padding": {
            "top": 0,
            "left": 2,
            "right": 1
        }
    },

    "display": {
        "separator": "  ",
        "color": {
            "keys": "{{accent_ansi}}",
            "title": "{{accent_bright_ansi}}"
        },
        "brightColor": false,
        "size": {
            "binaryPrefix": "iec"
        }
    },

    "modules": [
        {
            "type": "title",
            "keyColor": "{{accent_bright_ansi}}",
            "format": "{user-name}@{host-name}"
        },
        "separator",
        {
            "type": "os",
            "key": "󰣇 OS      ",
            "keyColor": "{{accent_ansi}}",
            "format": "{pretty-name} {version}"
        },
        {
            "type": "host",
            "key": "󰟀 Host    ",
            "keyColor": "{{accent_ansi}}",
            "format": "{name}"
        },
        {
            "type": "kernel",
            "key": " Kernel  ",
            "keyColor": "{{accent_ansi}}",
            "format": "{release}"
        },
        {
            "type": "uptime",
            "key": "󰅐 Uptime  ",
            "keyColor": "{{accent_ansi}}"
        },
        {
            "type": "packages",
            "key": "󰏗 Packages",
            "keyColor": "{{accent_ansi}}"
        },
        {
            "type": "shell",
            "key": " Shell   ",
            "keyColor": "{{accent_ansi}}",
            "format": "{pretty-name} {version}"
        },
        {
            "type": "wm",
            "key": "󱂬 WM      ",
            "keyColor": "{{accent_ansi}}",
            "format": "{pretty-name} {version}"
        },
        {
            "type": "terminal",
            "key": " Terminal",
            "keyColor": "{{accent_ansi}}",
            "format": "{pretty-name} {version}"
        },
        {
            "type": "display",
            "key": "󰍹 Display ",
            "keyColor": "{{accent_ansi}}",
            "compact": true
        },
        "separator",
        {
            "type": "cpu",
            "key": " CPU     ",
            "keyColor": "{{accent_bright_ansi}}",
            "format": "{name} ({cores-logical}) @ {freq-max}",
            "temp": true
        },
        {
            "type": "gpu",
            "key": "󰍛 GPU     ",
            "keyColor": "{{accent_bright_ansi}}",
            "format": "{name}",
            "detectionMethod": "pci"
        },
        {
            "type": "memory",
            "key": "󰘚 Memory  ",
            "keyColor": "{{accent_bright_ansi}}",
            "format": "{used} / {total} ({percentage})"
        },
        {
            "type": "disk",
            "key": "󰋊 Disk    ",
            "keyColor": "{{accent_bright_ansi}}",
            "folders": "/",
            "format": "{size-used} / {size-total} ({size-percentage})"
        },
        {
            "type": "localip",
            "key": "󰩟 IP      ",
            "keyColor": "{{accent_bright_ansi}}",
            "showIpv6": false,
            "compact": true
        },
        "separator",
        {
            "type": "colors",
            "paddingLeft": 2,
            "symbol": "circle"
        }
    ]
}
