# {{group_name}} – Hyprland Theme
# Generated by generate-themes.sh

# ==============================================================================
# Accent Colors
# ==============================================================================
$accent_primary   = rgb({{accent}})    # Primary accent – active borders, highlights
$accent_secondary = rgb({{accent_secondary}})    # Secondary accent – gradient

# ==============================================================================
# Surface Colors
# ==============================================================================
$surface_bg       = rgb({{bg_base}})    # Base background
$surface_0        = rgb({{bg_surface}})    # Surface – inactive borders
$surface_border   = rgb({{bg_surface}})    # Inactive window border

# ==============================================================================
# Shadow
# ==============================================================================
$shadow_color     = rgba({{shadow}}) # Drop-shadow effect

# ==============================================================================
# Text
# ==============================================================================
$text_primary     = rgb({{text}})    # Main text color
$text_subtext     = rgb({{text_sub}})    # Secondary text
