# {{group_name}} – Kitty Terminal Theme
# Generated by generate-themes.sh

# Colors
foreground              #{{text}}
background              #{{bg_base}}
selection_foreground    #{{bg_base}}
selection_background    #{{pink}}

# Cursor
cursor                  #{{text}}
cursor_text_color       #{{bg_base}}

# URL
url_color               #{{pink}}

# Window borders
active_border_color     #{{accent}}
inactive_border_color   #{{text_dim}}
bell_border_color       #{{yellow}}

# Tab bar
active_tab_foreground   #{{bg_base}}
active_tab_background   #{{accent_secondary}}
inactive_tab_foreground #{{text}}
inactive_tab_background #{{bg_surface}}
tab_bar_background      #{{bg_base}}

# Normal colors
color0  #{{bg_overlay}}
color1  #{{red}}
color2  #{{green}}
color3  #{{yellow}}
color4  #{{blue}}
color5  #{{magenta}}
color6  #{{cyan}}
color7  #{{text_sub}}

# Bright colors
color8  #{{text_dim}}
color9  #{{red}}
color10 #{{green}}
color11 #{{yellow}}
color12 #{{blue}}
color13 #{{magenta}}
color14 #{{cyan}}
color15 #{{text_sub}}
