/* {{group_name}} – Waybar Theme
 * Generated by generate-themes.sh
 * Copied to ~/.config/waybar/style.css by theme-toggle.sh
 */

* {
    font-family: "JetBrainsMono Nerd Font", "JetBrains Mono", monospace;
    font-size: 13px;
    border: none;
    border-radius: 0;
    min-height: 0;
    margin: 0;
    padding: 0;
}

window#waybar {
    background: rgba({{bg_base_r}}, {{bg_base_g}}, {{bg_base_b}}, 0.88);
    color: #{{text}};
    border-radius: 14px;
    border: 1px solid rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.15);
    transition: all 0.3s ease;
}

window#waybar.hidden {
    opacity: 0.2;
}

tooltip {
    background: rgba({{bg_base_r}}, {{bg_base_g}}, {{bg_base_b}}, 0.95);
    border: 1px solid rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.3);
    border-radius: 10px;
    color: #{{text}};
}

tooltip label {
    color: #{{text}};
}

#custom-launcher {
    font-size: 18px;
    color: #{{accent}};
    padding: 0 12px;
    margin: 4px 2px 4px 6px;
    border-radius: 10px;
    background: rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.1);
    transition: all 0.3s ease;
}

#custom-launcher:hover {
    background: rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.25);
    color: #{{accent_bright}};
}

#workspaces {
    margin: 4px 4px;
    padding: 0 4px;
    border-radius: 10px;
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.6);
}

#workspaces button {
    padding: 0 8px;
    color: #{{text_dim}};
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.35);
    border-radius: 8px;
    margin: 2px;
    transition: all 0.2s ease;
}

#workspaces button:hover {
    background: rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.15);
    color: #{{text}};
}

#workspaces button.active {
    color: #{{accent}};
    background: rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.2);
    font-weight: bold;
}

#workspaces button.urgent {
    color: #{{red}};
    background: rgba({{red_r}}, {{red_g}}, {{red_b}}, 0.15);
}

#submap {
    padding: 0 10px;
    color: #{{yellow}};
    font-style: italic;
}

#mpris {
    color: #{{accent_secondary}};
    padding: 0 12px;
    margin: 4px 2px;
    border-radius: 10px;
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.5);
    transition: all 0.2s ease;
}

#mpris:hover {
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.85);
}

#pulseaudio,
#backlight,
#network,
#battery,
#clock {
    padding: 0 12px;
    margin: 4px 2px;
    border-radius: 10px;
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.5);
    color: #{{text}};
    transition: all 0.2s ease;
}

#pulseaudio:hover,
#backlight:hover,
#network:hover,
#battery:hover,
#clock:hover {
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.85);
}

#pulseaudio { color: #{{green}}; }
#pulseaudio.muted { color: #{{text_dim}}; }
#backlight { color: #{{yellow}}; }
#network.connected, #network.wifi { color: #{{cyan}}; }
#network.disconnected { color: #{{red}}; }
#battery { color: #{{green}}; }
#battery.warning { color: #{{yellow}}; }
#battery.critical { color: #{{red}}; animation: blink 1s linear infinite; }
#battery.charging { color: #{{green}}; }
#clock { color: #{{accent_secondary}}; font-weight: bold; }

@keyframes blink {
    0%   { color: #{{red}}; }
    50%  { color: #{{orange}}; }
    100% { color: #{{red}}; }
}

#tray {
    padding: 0 8px;
    margin: 4px 2px;
    border-radius: 10px;
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.5);
}

#tray > .passive { -gtk-icon-effect: dim; }
#tray > .needs-attention { -gtk-icon-effect: highlight; }

#custom-caffeine {
    color: #{{text_dim}};
    padding: 0 10px;
    margin: 4px 2px;
    border-radius: 10px;
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.5);
    font-size: 14px;
    transition: all 0.3s ease;
}

#custom-caffeine:hover {
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.85);
}

#custom-caffeine.active {
    color: #{{yellow}};
    background: rgba({{yellow_r}}, {{yellow_g}}, {{yellow_b}}, 0.1);
}

#custom-caffeine.active:hover {
    background: rgba({{yellow_r}}, {{yellow_g}}, {{yellow_b}}, 0.25);
    color: #{{yellow_bright}};
}

#custom-power {
    color: #{{red}};
    padding: 0 10px;
    margin: 4px 6px 4px 2px;
    border-radius: 10px;
    background: rgba({{red_r}}, {{red_g}}, {{red_b}}, 0.1);
    font-size: 13px;
    transition: all 0.3s ease;
}

#custom-power:hover {
    background: rgba({{red_r}}, {{red_g}}, {{red_b}}, 0.25);
    color: #{{red_bright}};
}

#custom-notif-toggle {
    color: #{{text}};
    padding: 0 10px;
    margin: 4px 2px;
    border-radius: 10px;
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.5);
    font-size: 14px;
    transition: all 0.3s ease;
}

#custom-notif-toggle:hover {
    background: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.85);
}

#custom-notif-toggle.paused {
    color: #{{text_dim}};
}
