/* {{group_name}} – Wofi Theme
 * Generated by generate-themes.sh
 * Symlinked to ~/.config/wofi/style.css by theme-toggle.sh
 */

window {
    background-color: rgba({{bg_base_r}}, {{bg_base_g}}, {{bg_base_b}}, 0.95);
    border: 1px solid rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.25);
    border-radius: 16px;
    margin: 0;
    padding: 0;
}

#inner-box,
#outer-box {
    background: transparent;
    padding: 8px;
}

#input {
    background-color: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 0.8);
    border: 1px solid rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.3);
    border-radius: 10px;
    color: #{{text}};
    padding: 8px 14px;
    margin: 8px;
    font-family: "JetBrainsMono Nerd Font", monospace;
    font-size: 14px;
    caret-color: #{{accent}};
    outline: none;
}

#input:focus {
    border-color: rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.6);
    background-color: rgba({{bg_surface_r}}, {{bg_surface_g}}, {{bg_surface_b}}, 1.0);
}

#scroll {
    background: transparent;
    margin: 0 4px;
}

#entry {
    background: transparent;
    border-radius: 10px;
    padding: 6px 12px;
    margin: 2px 4px;
    transition: all 0.15s ease;
}

#entry:hover {
    background-color: rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.1);
}

#entry:selected,
#entry.selected {
    background-color: rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.2);
    border: 1px solid rgba({{accent_r}}, {{accent_g}}, {{accent_b}}, 0.3);
}

#text {
    color: #{{text}};
    font-family: "JetBrainsMono Nerd Font", monospace;
    font-size: 13px;
}

#text:selected {
    color: #{{accent}};
    font-weight: bold;
}

#img {
    margin-right: 10px;
}
